### ISSUE TITLE
Add API for focusing username field

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-login#114]
In a typical use case, you'd want to be able to start typing your username immediately, instead of clicking on the input field first. `autofocus` was removed from the web component side here: https://github.com/vaadin/vaadin-login/issues/33 , but there should be a server-side way of setting the focus on the username instead of relying on `UI.getCurrent().getPage().executeJavaScript("document.getElementById(\"vaadinLoginUsername\").focus();");` or such.

**Comment by georgebina** [comment]
Something like this seems to work for me
```
if (username instanceof Focusable) {
  ((Focusable)username).focus();
}
```
HTH,
George

**Comment by rolfsmeds** [comment]
Closing in favor of https://github.com/vaadin/vaadin-login/issues/121
