### ISSUE TITLE
AbstractLogin is using a deprecated API

### ISSUE THREAD

**Issue by tulioag** [vaadin/vaadin-login#115]
`Element.synchronizeProperty` has been deprecated in favor of `addPropertyChangeListener` or `DomListenerRegistration.synchronizeProperty`. The deprecated method is called in AbstractLogin's constructor. We should use the non-deprecated API.

**Comment by web-padawan** [comment]
Fixed by https://github.com/vaadin/vaadin-login-flow/pull/85.
