### ISSUE TITLE
Auto-focus username field (with opt-out option)

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/vaadin-login#121]
## Description
Username field gets focus by default. API provided to opt out of this behavior.

## Use cases
As a user
I want to start typing my username immediately when the login form appears
So that I can log in quickly

As a user of a UI to which Login is not the main entrypoint, but required only for a specific feature
I don't want the Login component to steal focus away from some more important element
So that I can interact with the rest of the UI without distractions

## Acceptance criteria
- [ ] By default, focus is automatically set to the username field when the Login component is rendered
- [ ] The username field's focus is rendered with the focus-ring to make it visible
- [ ] Web component has `no-autofocus` attribute / `noAutofocus` property that disables the default behavior
- [ ] Flow component has corresponding `setAutoFocus(boolean)` (and corresponding getter).
- [ ] PR for documentation update to https://vaadin.com/docs/latest/ds/components/login

## General criteria
- [ ] UX/DX tests in Alpha 

- [ ] Documentation: 

- [ ] How to test? 

- [ ] Limitations:

**Comment by jouni** [comment]
After this change, it’s quite impossible to read the docs in https://vaadin.com/docs/latest/ds/components/login

**Comment by web-padawan** [comment]
We probably should update docs to use `no-autofocus` to code examples and mention that it's for demo only.
