### ISSUE TITLE
Add a callback when user submits the form

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/vaadin-login#13]
- The callback provides the username and passwors fields
- Developer can set `action` for the form `POST`
- If developer doesn't provide an `action`, a custom event should be sent

**Comment by Legioth** [comment]
> If developer doesn't provide an `action`, a custom event should be sent

This is not how vanilla HTML forms work. Instead, an event is always fired, and then the action is used (if present) unless an event listener has done `event.preventDefault()`.

**Comment by DiegoCardoso** [comment]
Hmm. That makes sense. 

So with that in mind it would mean that before calling `this.$.loginForm.submit()`, we should ckeck whether `action` is present or `event.defaultPrevented` is `true` here https://github.com/vaadin/vaadin-login/blob/master/src/vaadin-login.html#L230.

**Comment by alvarezguille** [comment]
I'm not sure if that was the intention or just that:
* `loginForm.submit`is always called
* on pre-submit we dispatch the custom event
* and prevent default on custom event prevents default on for pre-submit

this way there's always an event and if default is not prevented  request will happen

this would be the vanilla way, but request needs to be prevented even if action wasn't defined

opinions @Legioth

**Comment by DiegoCardoso** [comment]
I created a solution proposal in this PR https://github.com/vaadin/vaadin-login/pull/43 which now dispatch the `login` event regardless `action` is defined or not. 

Then, user can perform any action and call `event.preventDefault()` so it will prevent the synchronous POST call. 

Note that `event.preventDefault()` has no action if called inside a different thread, so user won't be able to perform a `fetch` and make the call inside the callback, for instance.
