### ISSUE TITLE
Scroll bar doesn't appear on small viewport in IE11

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-login#36]
Scroll bar doesn't appear and forgotPassword button and footer are overlapping the form content.

![screenshot 2018-11-26 at 13 44 26](https://user-images.githubusercontent.com/28781210/49015836-ee44c580-f18c-11e8-9850-58fceba417c0.png)

Noticed that the following rule makes IE not to show a scroll bar
```
[part="form"] {
  display: flex;
}
```

**Comment by jouni** [comment]
All the elements inside the form should have `flex: none`.

**Comment by DiegoCardoso** [comment]
This issue seems to be gone now.

<img width="1008" alt="screenshot 2018-12-13 at 16 36 04" src="https://user-images.githubusercontent.com/262432/49959612-384fda00-fef5-11e8-9821-33ac01c3a19c.png">
