### ISSUE TITLE
Add password recovery instructions

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/vaadin-login#4]
- Developer can show/hide the "Forgot password" button
- Component should provide a callback (event) when the button is clicked
- Developer is responsible for create how the instructions will be present to user

**Comment by DiegoCardoso** [comment]
The instruction can be HTML content

**Comment by knoobie** [comment]
This should also be possible for username/email. Do you want me to create an "issue"?

**Comment by tulioag** [comment]
@knoobie There is only one command for this functionality. For username/email recovery you could rename the forgot password link to something suitable.The logic of the actual recovery is outside the scope of this element.

**Comment by knoobie** [comment]
There is the problem, most Login Forms have two functions for this. 

See: https://login.oracle.com/oaam_server/login.do (Click on the question mark next to the fields.)

**Comment by tulioag** [comment]
I don't know if most. Facebook, Twitter and Github only have one, for example.

**Comment by knoobie** [comment]
I see your point. ;) But as a framework, both (only one and two functions) should be possible.

**Comment by tulioag** [comment]
I see your point too. I suggest you create an issue about it. If there is enough interest it may be included at some point.
