### ISSUE TITLE
Support setting theme for vaadin-login-overlay-wrapper

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-login#63]
There is no way to define theme attribute for `vaadin-login-overlay-wrapper`, since it doesn't receive the value from `vaadin-login-overlay`.
Might be useful if the `theme` would be propagated to both `vaadin-login-overlay-wrapper` and `vaadin-login`

**Comment by web-padawan** [comment]
The `theme` propagation to `vaadin-login-overlay-wrapper` was implemented in https://github.com/vaadin/vaadin-login/pull/62/commits/445672b7f581039f09438c7a013d70df46efb372. Closing.
