### ISSUE TITLE
Password field is shown without styling when using default overlay

### ISSUE THREAD

**Issue by tulioag** [vaadin/vaadin-login#64]
When adding `<vaadin-login-overlay opened></vaadin-login-overlay>` to a project, the password field will be shown without styling, like so:

![error](https://user-images.githubusercontent.com/28783969/50775897-223cfb80-12a0-11e9-8136-81a5d89c34b6.png)

Expected:
![expected](https://user-images.githubusercontent.com/28783969/50775928-3aad1600-12a0-11e9-9c5f-9d2d0c973fe0.png)

**Comment by alexberazouski** [comment]
https://github.com/vaadin/vaadin-themable-mixin/issues/40 
the issue is caused by the exception in themable-mixin
