### ISSUE TITLE
Login fields should disable autocapitalize, autocomplete, and spellcheck

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-login#70]
Currently, the email/username field capitalizes the first letter (at least on iOS), and shows a red underline if I write a non-English word in it.

**Comment by jouni** [comment]
Did I really write “disable autocomplete” in the title?! 🤦‍♂️ 

I hope you didn’t do that 😅

**Comment by alexberazouski** [comment]
@jouni 
Actually, browsers ignore `autocomplete=off` for login fields.

Will revert that
