### ISSUE TITLE
How does the login work in vaadin bakery app

### ISSUE THREAD

**Issue by sudipta1411** [vaadin/vaadin-login#94]
I am new to vaadin JAVA framework. I am trying to understand the bakery app code. In `LoginView.java` there is a call to `setAction('login')`, which takes care of the login authorization. I want to add a new username and password. Can someone please shed a light how the app is successfully authorizing login credentials.

**Comment by web-padawan** [comment]
Hello, sorry for not answering earlier. The Bakery starter is using Spring Security. If you have a subscription and access to the code, please check out `SecurityUtils.java`.

See also our tutorial [Securing your app with Spring Security](https://vaadin.com/learn/tutorials/securing-your-app-with-spring-security/), which is a guide to Spring Security with Vaadin 14+ by our colleague Paul. It provides an example of setting up a form-based login view.
