### ISSUE TITLE
Integration with AWS Cognito

### ISSUE THREAD

**Issue by ronnyroeller** [vaadin/vaadin-login#97]
Does anybody have an example how to integrate `<vaadin-login>` with AWS Cognito?

**Comment by TedGraham** [comment]
Did you find anything?  I also need to integrate with AWS Cognito.  -Ted

**Comment by web-padawan** [comment]
This is a UI component that does not provide any integrations. 
The only API we have are two [events](https://cdn.vaadin.com/vaadin-login/1.0.1/#/elements/vaadin-login-form#events):

- `login` event dispatched when user submits the login
- `forgot-password` event dispatched when user clicks the "Forgot password" button.

We are not going to provide any integrations at the moment. And if we do, that will be out of scope for this component. We might consider publishing a tutorial instead.

So I'm closing this issue as there is nothing for us to do here.

**Comment by TedGraham** [comment]
I would certainly like to see a tutorial on integrating Cognito, preferably using their "hosted UI".  I thought it would be simple to get it to work but am still having trouble.  

    On Tuesday, February 11, 2020, 01:09:47 PM MST, Serhii Kulykov <notifications@github.com> wrote:  
 
 
This is a UI component that does not provide any integrations.
The only API we have are two events:
   
   - login event dispatched when user submits the login
   - forgot-password event dispatched when user clicks the "Forgot password" button.

We are not going to provide any integrations at the moment. And if we do, that will be out of scope for this component. We might consider publishing a tutorial instead.

So I'm closing this issue as there is nothing for us to do here.
