### ISSUE TITLE
vaadin-text-field dependency needs to be updated

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-login#98]
Right now the dep is at 2.3
```
"vaadin-text-field": "vaadin/vaadin-text-field#^2.3.0",
```
This creates bundling issues when using other vaadin components like vaadin-combo-box (since 5.0.1):
```
"vaadin-text-field": "vaadin/vaadin-text-field#^2.4.3",
```
webpack throws ye olde duplicates error because it needs to include both versions inteh bundles:
```
DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-text-field" has already been used with this registry
```
@web-padawan I imagine this is a pretty straight forward update? There may be other components that need updating too I guess. These were just the two I found in conflict.

**Comment by web-padawan** [comment]
This should be generally not required, as long as both versions can be resolved to a latest one when performing a fresh `npm install`. 

The duplicate dependencies problem rather happens randomly, i.e. when updating version of previously installed component, or installing a new component.

**Comment by moderndeveloperllc** [comment]
@web-padawan But it can't be resolved as the 2.4.x branch can't fulfill the the requirements for `"vaadin/vaadin-text-field#^2.3.0"`. This is an issue with bundling via webpack/rollup/etc as both versions get included in the bundles.

**Comment by DiegoCardoso** [comment]
Isn't there any way to resolve dependencies on the webpack side?

**Comment by moderndeveloperllc** [comment]
@DiegoCardoso Not one that works for web components. If this was just a js library, then it wouldn't be an issue as each conflicting version would reside in a different bundle. But as you know element registration is global, so residing in separate bundles doesn't help with SPA routers like `vaadin-router` where navigation is an additive process.

**Comment by moderndeveloperllc** [comment]
@web-padawan @DiegoCardoso I'm an idiot. OK, it's resolving properly now for some reason. Version 2.4.x **_will_** fulfill `vaadin/vaadin-text-field#^2.3.0`. I had removed my node_modules folder and done a yarn install yesterday, and it didn't work, but doing it again today worked fine! yarn can be very odd at time. This is what my lock file looked like:
```
-"@vaadin/vaadin-text-field@^2.1.1", "@vaadin/vaadin-text-field@^2.3.0":
-  version "2.3.8"
-  resolved "https://registry.yarnpkg.com/@vaadin/vaadin-text-field/-/vaadin-text-field-2.3.8.tgz#264d9d62ab04a46bb4dfeceebd8caee9b189a4bb"
-  integrity sha512-BuEckLsr0Ezpwx8PspQB3e3cW6SlNENlc2620ufPl0HSkk4FsyZlTlITAtnwAXNRKR1xCyMUpti4/MwZUDoc7A==
-  dependencies:
-    "@polymer/polymer" "^3.0.0"
-    "@vaadin/vaadin-control-state-mixin" "^2.1.1"
-    "@vaadin/vaadin-element-mixin" "^2.0.0"
-    "@vaadin/vaadin-lumo-styles" "^1.2.0"
-    "@vaadin/vaadin-material-styles" "^1.2.0"
-    "@vaadin/vaadin-themable-mixin" "^1.2.1"
-
-"@vaadin/vaadin-text-field@^2.4.3":
-  version "2.4.9"
-  resolved "https://registry.yarnpkg.com/@vaadin/vaadin-text-field/-/vaadin-text-field-2.4.9.tgz#419efb8f510cc0cf5178a5753c69450ef9f542c8"
-  integrity sha512-tGR1UbF5CURFE1B6mTdseHu1uFCwBxDE20F4+DoLj0b0c3qIV8kHNSJ2qq4GCvxKRGHML8hGcmOs+y4VkWpRvw==
+"@vaadin/vaadin-text-field@^2.1.1", "@vaadin/vaadin-text-field@^2.3.0", "@vaadin/vaadin-text-field@^2.4.3":
+  version "2.4.10"
+  resolved "https://registry.yarnpkg.com/@vaadin/vaadin-text-field/-/vaadin-text-field-2.4.10.tgz#1e0bd28e0b4a2a2e0b84e5dc8b8c1747a31a64ae"
+  integrity sha512-JdXoIO2P4vYvBRWEmCNwzYlmyktIN0QFFA8royCFQMqxaXM2WxDIzLZ+1XtoHIjy8Bti4y1gwSzrqx20p510Hg==
```
Why it decided to go from having two versions to correctly having only one is beyond me really. I didn't change my `package.json` smh
